# Generated by Django 5.2.3 on 2025-07-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden'), ('ARCHIVED', 'Archived')], default='VISIBLE', max_length=100),
        ),
    ]
